- name: "Testing ansible out"
  hosts: localhost
  connection: local 
  tasks:

  - name: Update and upgrade homebrew
    ansible.builtin.package:
      use: homebrew
      update_homebrew: true
      upgrade: true

  - name: Install dev tools
    ansible.builtin.package:
      name:
        - gh
        - git
        - zola
        - wget
        - curl
      state: present

  - name: Install browsers
    community.general.homebrew:
      name:
        - firefox 
        - chromium 
      install_options: cask
      state: present

  # TODO: zsh and alacritty setup?
  - name: Install shell (zsh)
    ansible.builtin.package:
      name: zsh
      state: present

  # only on mac
  - name: Install terminal (iterm2)
    community.general.homebrew:
      name: iterm2
      install_options: cask
      state: present

  - name: Install terminal/navigation-related programs
    ansible.builtin.package:
      name:
        - neofetch
        - ripgrep
        - eza
        - fzf
        - tree
        - neovim
        - lazygit
      state: present

  - name: Install media-related programs
    ansible.builtin.package:
      name:
        - scrot
        - mpv
        - ffmpeg
        - vlc
      state: present
