- name: "Init machine"
  hosts: localhost
  connection: local 

  tasks:
    - name: Update and upgrade homebrew
      ansible.builtin.package:
        use: homebrew
        update_homebrew: true
        upgrade: true

    - name: Install dev tools
      ansible.builtin.package:
        name:
          - gh
          - git
          - zola
          - wget
          - curl
        state: present

    # TODO: upgrade proper zsh setup (changing shell)
    - name: Install shell (zsh)
      ansible.builtin.package:
        name: zsh
        state: present

    - name: Install terminal/navigation-related programs
      ansible.builtin.package:
        name:
          - zellij
          - neofetch
          - ripgrep
          - eza
          - fzf
          - tree
          - neovim
          - lazygit
        state: present

    - name: Install media-related programs
      ansible.builtin.package:
        name:
          - mpv
        install_options: formula
        state: present

    - name: Install terminal (alacritty)
      register: res
      failed_when: 
        - '"already installed" not in res.msg'
      ansible.builtin.package:
        name: alacritty
        install_options: cask,no-quarantine
        state: present

    - name: Install casks
      register: res
      failed_when: 
        - '"already installed" not in res.msg'
      ansible.builtin.package:
        name:
          - firefox 
          - chromium 
          - vlc
          - obsidian
        install_options: cask
        state: present
