[colors.vi_mode_cursor]
cursor = "CellForeground"
text = "CellBackground"

[font]
size = 17.0

[font.normal]
family = "BerkeleyMono Nerd Font"
style = "Regular"

[window]
decorations_theme_variant = "Dark"
dynamic_padding = true
dynamic_title = true
opacity = 0.75

[window.padding]
x = 2
y = 2
