set preview_files true
set preview_directories true
set collapse_preview false
set draw_borders both
set show_hidden false
set hidden_filter ^\.|\.pyc$|\.pyo$|\.rbc$|\.rbo$|\.class$|\.o$|__pycache__
set sort natural
set sort_case_insensitive true
set sort_directories_first true

set use_preview_script true
set preview_script ~/.config/ranger/scope.sh

set unicode_ellipsis true
set show_cursor false
set update_title true
set update_tmux_title true
set tilde_in_titlebar true
set max_history_size 20
set max_console_history_size 50

set mouse_enabled true
set padding_right true

set colorscheme default

map <C-f> fzf_select
map D shell mv %s ~/.local/share/Trash/
map <C-h> toggle_hidden

alias e edit
alias q quit
alias qall quitall
